# Generated by Django 3.2.5 on 2021-07-06 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите название события', max_length=124, verbose_name='событие')),
                ('start_date', models.DateTimeField(db_index=True, help_text='введите дату и время начала события', verbose_name='начало события')),
                ('end_date', models.DateTimeField(blank=True, help_text='введите дату и время окончания события', verbose_name='окончание события')),
                ('reminder_before', models.SmallIntegerField(blank=True, help_text='выберите время напоминания', null=True, verbose_name='напоминание о событии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
