# Generated by Django 3.2.5 on 2021-07-13 10:18

from django.db import migrations
from event.constants import countries
from event.models import Country


def add_country (apps, schema_editor):
    for country in countries:
        new_country = Country()
        new_country.name = country
        new_country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210713_1317'),
    ]

    operations = [
        migrations.RunPython(add_country),
    ]
