# Generated by Django 3.2.5 on 2021-07-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_load_intial_data_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='название государственного праздника')),
                ('start_date', models.DateTimeField(db_index=True, verbose_name='начало праздника')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='окончание праздника')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.country')),
            ],
        ),
    ]
