# Generated by Django 3.2.5 on 2021-08-19 15:11

from django.db import migrations

from event.constants import countries
from event.service import import_from_ics


def add_public_holidays(apps, schema_editor):
    for country in countries:
        import_from_ics(country)


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_publicholiday'),
    ]

    operations = [
        migrations.RunPython(add_public_holidays)
    ]
