# Generated by Django 3.2.5 on 2021-07-15 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_publicholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('first_name', models.CharField(max_length=124, verbose_name='Имя')),
                ('Last_name', models.CharField(max_length=124, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
